name = "smart-bundle-boost"
client_id = "2a1aa0d9b96c76a1fff1dcac830b8b4b"
application_url = "https://smart-bundle-boost-eight.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bundle-test-20220534.myshopify.com"

[access_scopes]
scopes = "write_products,read_orders,write_draft_orders,write_discounts"

[auth]
redirect_urls = [
  "https://smart-bundle-boost-eight.vercel.app/auth/callback",
  "https://smart-bundle-boost-eight.vercel.app/auth/shopify/callback"
]

[webhooks]
api_version = "2024-01"

[[webhooks.subscriptions]]
topics = ["customers/data_request"]
uri = "/api/webhooks/gdpr/customers-data-request"

[[webhooks.subscriptions]]
topics = ["customers/redact"]
uri = "/api/webhooks/gdpr/customers-redact"

[[webhooks.subscriptions]]
topics = ["shop/redact"]
uri = "/api/webhooks/gdpr/shop-redact"

[[webhooks.subscriptions]]
topics = ["app_subscriptions/update"]
uri = "/api/webhooks/app-subscription-update"

[pos]
embedded = false